### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by brandleesee** [GeekJosh/BertUI#6]
- Option for disabling the Shut Down button.
- The transparency between the icons becomes fixed in the sense that when the mouse cursor is in between two thumbnails, it does not switch the focus to the desktop or any window layered underneath BertUI.
- Option to enable/disable a 'close' button (to close BertUI).
- Activation by executable shortcuts (needed to give the 'maximize' command when the application opens

Thanks! After one whole year, I returned to this little piece of software.

**Comment by GeekJosh** [comment]
Hey thanks for the suggestions, I'll try to add them to the next version

**Comment by brandleesee** [comment]
Repository seems abandoned.
Website no longer existent.
Closing
